language: python
python:
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
install:
  - "pip install -r requirements.txt"
script:
  - "python epiphyte_test.py"
